version: '3.5'
services:
  angular:
    container_name: angular
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    working_dir: /var/www
    ports:
      - 4200:4200
    volumes:
      - .:/var/www
    command: "npm start"
    tty: true
    restart: on-failure
